# Use the official TensorFlow image with GPU support
FROM tensorflow/tensorflow:latest-gpu-jupyter

# Install any additional packages you need here
RUN pip install --upgrade pip \
    && pip install tensorflow-gpu
